# Generated by Django 4.2.13 on 2024-07-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(upload_to='news_image', verbose_name='Фотография')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='Описание')),
                ('small_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Небольшое описание')),
                ('include_photo', models.ImageField(upload_to='news_image_include')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('news_id',),
            },
        ),
    ]
