# Generated by Django 4.2.13 on 2024-07-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_created_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Описание'),
        ),
    ]
