# Generated by Django 4.2.13 on 2024-07-01 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Имя категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('icon', models.ImageField(upload_to='icon_category', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(upload_to='products_images', verbose_name='Фотография')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='Описание')),
                ('notes', models.CharField(blank=True, max_length=300, null=True, verbose_name='Примечания')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('product_id',),
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, verbose_name='Обозначение')),
                ('folded_height', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Высота сложенной мачты, м')),
                ('unfolded_height', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Высота развернутой мачты, м')),
                ('mass', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Масса мачты, кг')),
                ('load_min', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Масса поднимаемого груза не менее, кг')),
                ('load_max', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Масса поднимаемого груза не более, кг')),
                ('sections', models.PositiveIntegerField(verbose_name='Число колен')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passports', to='goods.products')),
            ],
        ),
    ]
