# Generated by Django 4.2.13 on 2024-07-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_categories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='excel',
            field=models.FileField(blank=True, upload_to='excel_table', verbose_name='Excel Таблица'),
        ),
    ]
