# Generated by Django 4.2.13 on 2024-07-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_products_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Примечания'),
        ),
    ]
