# Generated by Django 4.2.13 on 2024-07-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_products_description_alter_products_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='notes',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Примечания'),
        ),
    ]
