# Generated by Django 4.2.13 on 2024-07-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_products_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passport',
        ),
    ]
