# Generated by Django 4.2.13 on 2024-07-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_delete_passport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='excel',
            new_name='dowload_file',
        ),
    ]
