# Generated by Django 4.2.13 on 2024-07-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_rename_excel_products_dowload_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='dowload_file',
            new_name='download_file',
        ),
    ]
