# Generated by Django 4.2.13 on 2024-07-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_rename_dowload_file_products_download_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='photogallery',
            field=models.ImageField(blank=True, upload_to='products_gallery/', verbose_name='Фотогалерея'),
        ),
    ]
