# Generated by Django 4.2.13 on 2024-07-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_products_photogallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photogallery',
            field=models.FileField(blank=True, upload_to='products_gallery/', verbose_name='Фотогалерея'),
        ),
    ]
