# Generated by Django 4.2.13 on 2024-07-12 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_alter_products_photogallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='photogallery',
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Название')),
                ('photogallery', models.ImageField(blank=True, upload_to='products_gallery/', verbose_name='Фотогалерея')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ('product_id',),
            },
        ),
    ]
