# Generated by Django 4.2.13 on 2024-07-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_remove_products_photogallery_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='product_id',
            new_name='product',
        ),
    ]
